In [30]:
import numpy as np

# Create a Matrix using Python

In [39]:
matrix = np.array([[1,2,3], [4,5,6]])
print(matrix)

[[1 2 3]
 [4 5 6]]


In [40]:
# Matrix with random value
rand_matrix = np.random.randint(100, size=(5,5))
rand_matrix

array([[90, 52, 92,  8,  6],
       [56, 85, 32, 51, 82],
       [77, 11, 50, 62, 63],
       [54, 22, 27, 38, 48],
       [29, 82, 10, 41, 10]])

In [33]:
# Zero Matrix

zero_matrix = np.zeros([5,5], dtype='int')
zero_matrix

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [41]:
# One Matrix

one_matrix = np.ones([5,5], dtype='int')
one_matrix

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [42]:
# Identity Matrix

identity_matrix = np.eye(5,5, dtype='int')
identity_matrix

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [43]:
# Transpose Matrix

matrix_t = np.array([[1,2,3], [4,5,6], [7,8,9]])
transpose_matrix = matrix_t.T

transpose_matrix

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

## Matrix operation in Python

In [44]:
# Matrix addition

# Type One
matrix1 = np.array([[1,2,3], [4,5,6]])
matrix2 = np.array([[2,3,4], [5,6,7]])

matrix_addition = matrix1 + matrix2
print(matrix_addition)

# Type Two

matrix_add = np.add(matrix1, matrix2)
print(matrix_add)

[[ 3  5  7]
 [ 9 11 13]]
[[ 3  5  7]
 [ 9 11 13]]


In [47]:
# Matrix Subtraction

# Type One
matrix_subtraction = matrix1 - matrix2
print(matrix_subtraction)

# Type Two
matrix_sub = np.subtract(matrix1, matrix2)
print(matrix_add)

[[-1 -1 -1]
 [-1 -1 -1]]
[[ 3  5  7]
 [ 9 11 13]]
